language: groovy
jdk:
  - oraclejdk7
branches:
  only:
    - master
before_install:
 curl -s get.gvmtool.net >> gvm.sh | sudo chmod 777 gvm.sh | sudo sh ./gvm.sh | sudo gvm install grails
script:
  grails test-app
